### ISSUE TITLE
Speech emotion recognition

### ISSUE THREAD

**Issue by Mi12Mi12Cu** [AbdulBasit-MrRobo/Real-Time-Speech-Emotion-Recognition#1]
Hello, Gooday. Am currently trying to carry out speech emotion recognition using your code but i keep getting this error.
![image](https://user-images.githubusercontent.com/82485291/129829621-f40d6695-ee02-4fb1-9176-2c7d5e09b9b9.png)
please can you help me

**Comment by AbdulBasit-MrRobo** [comment]
Greetings
Please change the path in the load_data function in glob call with where
your dataset is present.

Hope will now work for you

Thanks and Regards.
