### ISSUE TITLE
RuntimeError: Error opening 'C:\\Users\\Abdul\\Desktop\\DE Project\\DE-2A\\Implementation\\Predict-Record-Audio.wav': System error.

### ISSUE THREAD

**Issue by sofien00000** [AbdulBasit-MrRobo/Real-Time-Speech-Emotion-Recognition#2]
Hello i get that error in the title always  please help

**Comment by AbdulBasit-MrRobo** [comment]
Greetings,

Please change the path of file in record_predictAudio() function to the path of your .wav generated file. I think it should be generating in the same path as your .py file's.

Hope this works for you.

Thanks and regards

**Comment by sofien00000** [comment]
yes i figured this when i looked in the code thanks. But now i have this problem hope you can help me too:
raise NotFittedError(msg % {"name": type(estimator).__name__})
sklearn.exceptions.NotFittedError: This MLPClassifier instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

**Comment by AbdulBasit-MrRobo** [comment]
Before predicting, you must train the model.
Enter 1 before entering 2/3.
